---
- hosts: all
  become: yes
  tasks:
    - name: Install python-apt
      apt:
        name: python-apt
    - name: Update cache
      apt:
        update_cache: yes
    - name: Upgrade packages
      apt:
        upgrade: dist
